spring:
  jpa:
    hibernate:
      ddl_auto: update

  datasource:
    url: jdbc:mysql://board-db.cfau62iywdxj.ap-northeast-2.rds.amazonaws.com:3306/board
    username: admin
    password: qwer1234

  data:
    redis:
      host: board-redis.o01wzy.ng.0001.apn2.cache.amazonaws.com
      port: 6379